spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/newbit
    username: letsgetit
    password: letsgetit
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: newbit04
    password: yicjehjuajucwdqv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.springsecurity.query.dto

jwt:
  secret: LH9QZL8upsPBfuDY+Dkb1kT9DZIIUSuA2u4O6Lfi3mkEfeWtETpVTcR/8SMZdJWn/xNTuCQBE6rBvDXgnVmscQ==
  expiration: 1800000
  refresh-expiration: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
