server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://newbit-user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/api/v1/user/(?<segment>.*), /${segment}
        - id: feature-service
          uri: lb://newbit-feature-service
          predicates:
            - Path=/api/v1/feature/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH
          filters:
            - RewritePath=/api/v1/feature/(?<segment>.*), /${segment}

        # SockJS websocket 연결 (info, xhr 요청)

        - id: feature-service-sockjs
          uri: lb://newbit-feature-service
          predicates:
            - Path=/api/v1/feature/ws/**
            - Method=GET,POST,OPTIONS
          filters:
            - RewritePath=/api/v1/feature/ws/(?<segment>.*), /ws/${segment}
            -
        # 실제 WebSocket 업그레이드 요청

        - id: feature-service-ws
          uri: lb:ws://newbit-feature-service
          predicates:
            - Path=/api/v1/feature/ws/**
            - Method=GET
            - Header=Upgrade, websocket
          filters:
            - RewritePath=/api/v1/feature/ws/(?<segment>.*), /ws/${segment}
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  config:
    import: classpath:/bootstrap.yml
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
